### ISSUE TITLE
fileModelBrowser error

### ISSUE THREAD

**Issue by JamesWrigley** [buttleofx/ButtleOFX#140]
Hi there,
On starting ButtleOFX the browser window is solid grey and I can see these errors in the terminal:

```
➜  ButtleOFX_Alpha_Linux64_v2.0  ./run_buttleofx.sh 
--------------------------------------------------
QML_IMPORT_PATH: ./Qt5.2.0/gcc_64/qml:/home/james/src/ButtleOFX_Alpha_Linux64_v2.0/ButtleOFX/QuickMamba/quickmamba/../qml
"Qt Warning - invalid keysym: dead_actute" 
view <PyQt5.QtQml.QQmlEngine object at 0x7f94bd330640>
view <PyQt5.QtQml.QQmlEngine object at 0x7f94bd330640>
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/65-0-lohit-bengali.conf", line 32: unknown element "langset"
Fontconfig warning: "/etc/fonts/conf.d/69-gnu-free-sans.conf", line 24: unknown element "langset"
Fontconfig warning: "/etc/fonts/conf.d/69-gnu-free-serif.conf", line 24: unknown element "langset"
Traceback (most recent call last):
  File "/home/james/git/ButtleOFX/buttleofx/gui/browser/fileModelBrowser.py", line 363, in setFolder
    self.updateFileItems(folder)
  File "/home/james/git/ButtleOFX/buttleofx/gui/browser/fileModelBrowser.py", line 290, in updateFileItems
    dirs = [item.getFilename() for item in items if item.getType() == sequenceParser.eTypeFolder]
  File "/home/james/git/ButtleOFX/buttleofx/gui/browser/fileModelBrowser.py", line 290, in <listcomp>
    dirs = [item.getFilename() for item in items if item.getType() == sequenceParser.eTypeFolder]
AttributeError: 'Item' object has no attribute 'getType'
Traceback (most recent call last):
  File "/home/james/git/ButtleOFX/buttleofx/gui/browser/fileModelBrowser.py", line 363, in setFolder
    self.updateFileItems(folder)
  File "/home/james/git/ButtleOFX/buttleofx/gui/browser/fileModelBrowser.py", line 290, in updateFileItems
    dirs = [item.getFilename() for item in items if item.getType() == sequenceParser.eTypeFolder]
  File "/home/james/git/ButtleOFX/buttleofx/gui/browser/fileModelBrowser.py", line 290, in <listcomp>
    dirs = [item.getFilename() for item in items if item.getType() == sequenceParser.eTypeFolder]
AttributeError: 'Item' object has no attribute 'getType'
Traceback (most recent call last):
  File "/home/james/git/ButtleOFX/buttleofx/gui/browser/fileModelBrowser.py", line 363, in setFolder
    self.updateFileItems(folder)
  File "/home/james/git/ButtleOFX/buttleofx/gui/browser/fileModelBrowser.py", line 290, in updateFileItems
    dirs = [item.getFilename() for item in items if item.getType() == sequenceParser.eTypeFolder]
  File "/home/james/git/ButtleOFX/buttleofx/gui/browser/fileModelBrowser.py", line 290, in <listcomp>
    dirs = [item.getFilename() for item in items if item.getType() == sequenceParser.eTypeFolder]
AttributeError: 'Item' object has no attribute 'getType'
getBBox
```

Looking at the commit history, it seems this was introduced in 6311a51, so I'm guessing that my version of TuttleOFX/pysequenceParser is out of date? I'm still using the libs from the tarball on the website.
If so, how would I update them?

Thanks,
James

**Comment by fabiencastan** [comment]
Yes sorry, we have to provide the new binaries. I will do that ASAP.

**Comment by JamesWrigley** [comment]
Ah I see, thanks.
